language: php

php:
  - 7.1
  - nightly

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  allow_failures:
    - env: CODECOVERAGE=1 DEFAULT=0
    - php: nightly

  fast_finish: true

  include:
    - php: 7.1
      env: DEFAULT=1

    - php: 7.1
      env: CODECOVERAGE=1 DEFAULT=0

    - php: 7.1
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - composer self-update
  - git clone git://github.com/absalomedia/sassphp
  - cd sassphp
  - git submodule init
  - git submodule update
  - php install.php
  - make install
  - echo "extension=sass.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ..
  - composer install --prefer-dist --no-interaction

  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit --stderr; fi"
  - sh -c "if [ '$PHPSTAN' = '1' ]; then composer require --dev phpstan/phpstan:^0.8 && vendor/bin/phpstan analyse -c phpstan.neon -l 5 src; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml || true; fi"

after_success:
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then curl -s https://codecov.io/bash | bash || true; fi"

notifications:
  email: false